### ISSUE TITLE
How to do user authentication 

### ISSUE THREAD

**Issue by PeterZilz** [hannover-elm/website#17]
How is user authentication done in an Elm application?

* Using Cookies
* Using local storage
* Are there other approaches... 

How does it impact various aspects of an Elm app?

* Model
* Routing
* Security
* Server calls

**Comment by aforemny** [comment]
Hi @PeterZilz, I would be very interested in that as well! Especially, I am also interested in the two sides of this topic that is "how to do user authentication properly" and "how to do user authentication in Elm".

For the first question, I would also be interested in the differences between Cookies and JWT.

For the second question, I have been meaning to take a look at [elm-auth](https://github.com/the-sett/elm-auth).

Would you also like to present something here? Maybe we can team up and prepare a few presentations?!
